version: "3.9"
    
services:
   php:
     image: wiliehidayat87/php-dockerize-test-code:latest
     expose:
      - 9000
     restart: always
     extra_hosts:
      - "host.docker.internal:host-gateway"
     networks:
      - example
     deploy:
      replicas: 1
      mode: replicated

   nginx:
     restart: always
     image: nginx
     configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
     extra_hosts:
      - "host.docker.internal:host-gateway"
     ports:
      - 80:80
     networks:
      - example
     deploy:
      replicas: 1
      mode: replicated

   db:    
      image: mariadb  
      volumes: 
        -    mysql-data:/var/lib/mysql
      environment:  
       MYSQL_ROOT_PASSWORD: mariadb
       MYSQL_DATABASE: ecomdb 

configs:
  nginx_config:
    file: ./nginx/default.conf
networks:
  example:
    driver: overlay
    driver_opts:
      encrypted: "true"
volumes:
    mysql-data: